### ISSUE TITLE
Pipeline error in gstreamer 1.20.0 on macosx

### ISSUE THREAD

**Issue by sikang99** [notedit/gst-go-demo#4]
Recently gstreamer is upgraded to 1.20.0 by brew of mac x86 notebook.
After upgrade, the examples do not work as follows.
In gstreamer 1.18.5, they work well.
 
[ GSTREAMER ] shim init
[ GST ] program is linked against GStreamer 1.20.0
panic: pipeline error

goroutine 1 [running]:
main.main()
	/Users/stoney/coding/go/src/github.com/notedit/gst-go-demo/appsrc/main.go:15 +0x198
exit status 2

**Comment by sikang99** [comment]
The problem was solved by setting GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0.
Anyway Thanks for your source.

**Comment by notedit** [comment]
thanks
